### ISSUE TITLE
Get all Anle ids

### ISSUE THREAD

**Issue by HaHongDo** [HaHongDo/vbpl-web-crawl#4]

**Comment by HaHongDo** [comment]
Retrieve all VBPL ids from vbpl.vn using public search API to run other tasks

API: https://anle.toaan.gov.vn/webcenter/portal/anle/anle?hieuLuc=1&_afrLoop=9117215859295275&_afrWindowMode=0&Adf-Window-Id=w161xi2opc&_afrPage=0&_afrFS=16&_afrMT=screen&_afrMFW=959&_afrMFH=707&_afrMFDW=1536&_afrMFDH=864&_afrMFC=8&_afrMFCI=0&_afrMFM=0&_afrMFR=120&_afrMFG=0&_afrMFS=0&_afrMFO=0

**Comment by Minh0511** [comment]
https://anle.toaan.gov.vn/webcenter/portal/anle/anle?selectedPage=2&docType=AnLe&mucHienThi=9009&hieuLuc=1
